name: py37_min_maml
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - jupyter=1.0.0
  - jupyterlab=1.2.4
  - matplotlib=3.1.1
  - nb_conda_kernels=2.2.2
  - numpy=1.17.4
  - pandas=0.25.3
  - pip=19.3.1
  - python=3.7.5
  - pytorch=1.3.1
  - scipy=1.3.2
  - torchvision=0.4.2
